image: 192.168.0.31:5050/gitlab-instance-ccf8425a/quest

 
stages:          
  - test
  - build
  - deploy

test-job:
    stage: test
    script:
        - pip install . .[columns] .[ical] .[prompt] .[test] 
        - python3 -m pytest
   

     
        
build-job:
    stage: build
    script:
      - pip install .
      - topydo -v
    
deploy-job:
  stage: deploy
  script:
    - sshpass -p $PASSWORD ssh -o StrictHostKeyChecking=no kus@192.168.0.31 " mkdir $CI_JOB_ID && cd $CI_JOB_ID && git clone ssh://git@192.168.0.31:5012/gitlab-instance-ccf8425a/quest.git"
    - sshpass ssh kus@192.168.0.31 "cd $CI_JOB_ID/quest && sudo pip install ."
    - sshpass ssh kus@192.168.0.31 "topydo -v"
    - echo fucking done!
